Ensure samesite can be set on downstream applications
raveljs/ravel pull request #304
Opened 2020-10-21 16:41 UTC by ggayowsky

2020-10-21 20:04 UTC, plaliberte approved these changes

2020-10-22 03:50 UTC, Ghnuberath commented
This looks good, but you'll need to add the new param to the README under Core Parameters, indicating its purpose and default value.

2020-10-22 03:51 UTC, Ghnuberath requested changes
New param needs documentation in README

2020-10-23 05:47 UTC, Ghnuberath approved these changes

2020-10-23 06:17 UTC, merged